//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string Choice1 { get; set; }
        public bool IsCorrect { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
