//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AvailableQuestions
    {
        public int UserId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Question { get; set; }
        public Nullable<int> ChoiceId { get; set; }
        public string Choice { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
    }
}
