//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EClass
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_WrongAnswers
    {
        public int Id { get; set; }
        public int Expr1 { get; set; }
        public int Expr2 { get; set; }
        public string Name { get; set; }
        public bool IsCorrect { get; set; }
    }
}
